apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: EightApi
namespace: staging
bases:
  - ../../base
commonAnnotations:
  app: EightApi
  backstage.io/kubernetes-id: "EightApi"
commonLabels:
  app: EightApi
  backstage.io/kubernetes-id: "EightApi"
patchesStrategicMerge:
  - configmap_patch.yaml
  - deployment_patch.yaml